config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'users#index', as: :unauthenticated_root
    end
  end

  get 'categories/most_recent'
  get 'categories/most_ancient'

  resources :categories, only: %i[index new create show destroy update] do
    resources :payments, only: %i[index new create destroy update]
  end

  resources :users, only: %i[index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_many :categories, through: :category_payments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, presence: true, numericality: { greater_than: 0, less_than: 100_000_000 }
  validates :user_id, presence: true
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments or /payments.json
  def index
    @category = Category.find(params[:category_id])
    @payments = Payment.where(category_id: @category.id)
    @total_amount = @payments.sum(:amount)
  end

  # GET /payments/1 or /payments/1.json
  def show; end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments or /payments.json
  def create
    @payments = current_user.payments.new(payment_params)

    if @payments.save
      redirect_to category_payments_path, notice: 'Payment was successfully added'
    else
      render :new, alert: 'Failed to add payment'
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.permit(:name, :amount, :category_id)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Name:</strong>
    <%= payment.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= payment.category_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= payment.user_id %>
  </p>

</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<%= render "devise/shared/nav" %>
<div class="d-flex  justify-content-between">
   <%= link_to 'Back', categories_path, class: "btn btn-primary m-3"  %>
   <%= button_to "Delete", category_payment_path(category_id: @category.id, id: @category), method: :delete, class: 'bi bi-archive-fill btn btn-danger m-3' %>
</div>
<div class="card">
   <div class="card-body">
      <% if @payments.blank? %>
         <p>No payment are available at the moment</p>
      <% else %>
         <div class='top-card'>
            <% if @category.icon.present? %>
               <%= image_tag @category.icon %>
            <% else %>
               <%= image_tag "category.jpg" %>
            <% end %>
            <h1><%= @category.name %></h1>
         </div>
         <div class="border border-success p-2 border-opacity-10 mt-3">
            <p class='py-3'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
         </div>
         <hr />
         <ul>
            <% @payments.each do |payment| %>
               <li class="payments">
                  <a><%= payment.name %></a>
                  <a>$<%= payment.amount %></a>
               </li>
            <% end %>
         </ul>
         <hr />
      <% end %>
      <div class="d-flex justify-content-between">
         <p>Total Amount</p>
         <p>$<%= @total_amount %></p>
      </div>
   </div>
</div>

<div class="btn-wrapper d-grid gap-2 d-md-block">
  <button class="btn-main" type="button">
    <%= link_to "Add Transaction", new_category_payment_path %>
  </button>
</div>

app/views/payments/new.html.erb
<%= render 'devise/shared/nav'%>
<div class="card">
  <div class="card-body">
    <%= form_with model: @catagory_payment, url: category_payments_path do |f| %>
        <%= f.text_field :name, placeholder: 'Name', class:'form-control mb-3'%>
        <%= f.number_field :amount, placeholder: 'Amount', class: 'form-control mb-3'%>
        <%= fields_for(@category) do |cat| %>
            <%= cat.select :category_id, Category.all.map { |c| [c.name, c.id] }, {}, {class: 'form-select form-select-lg mb-3'} %>
        <% end %> 
        <button class="btn btn-outline-primary" type="submit">Add transaction</button>
    <% end %>
  </div>
</div>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>