config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'users#index', as: :unauthenticated_root
    end
  end

  get 'categories/most_recent'
  get 'categories/most_ancient'

  resources :categories, only: %i[index new create show destroy update] do
    resources :payments, only: %i[index new create destroy update]
  end

  resources :users, only: %i[index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :payments, dependent: :destroy

  has_one_attached :icon, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :user_id, presence: true

  def recent_payments
    payments.order(created_at: :desc).limit(5)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories or /categories.json
  def index
    @user = current_user
    @categories = current_user.categories.includes(:payments).order(id: :desc)
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  def most_recent
    @user = current_user
    @categories = Category.all
  end

  def most_ancient
    @user = current_user
    @categories = Category.all
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    add_category = current_user.categories.new(category_params)
    if add_category.save
      redirect_to categories_path, notice: 'Category was successfully added'
    else
      render :new, alert: 'Failed to add category'
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @user = current_user
    @category = Category.find(params[:id])

    if @category.destroy
      redirect_to categories_path, notice: 'Category was successfully deleted'
    else
      render :index, alert: 'Failed to delete category'
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= category.user_id %>
  </p>

</div>

app/views/categories/_form.html.erb
<div class="card">
    <div class="card-body">
        <%= form_with model: @category, url: categories_path do |f| %>
            <div class="mb-3">
                <%= f.file_field :icon, placeholder: "Add Icon", class: "form-control", type:"file", id:"formFile" %>
            </div>
            <%= f.text_field :name, placeholder: "Name", class: "form-control"%>
            <%= f.submit 'Add Category', class: 'btn-form'%>
        <% end %>
    </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="nav-card bg-primary">
    <%= render 'devise/shared/nav' %>
    <div class="nav-card-body mx-2">
        <%= link_to 'Oldest', categories_most_ancient_path, class: '' %>
        <%= link_to 'Recent', categories_most_recent_path, class: '' %>
    </div>
</div>
<div class="card">
    <div class="card-body">
    <p>Finances</p>
    </div>
</div>
<div class="card bg-light text-dark">
    <% @categories.each do |category| %>
        <div class="card-body">
            <div class="m-3 bg-light category-card shadow-sm bg-light rounded">
                <% if category.icon.present? %>
                    <%= image_tag category.icon, class: "catagory-photo" %>
                <% else %>
                    <%= image_tag "category.jpg", class: "catagory-photo" %>
                <% end %>
                <div class="trans-text">
                    <div class="trans-name">
                        <p class=""><%= link_to category.name, category_payments_path(category_id: category.id) %></p>
                        <p class="fw-bold">$<%= Payment.where(category_id: category.id).reduce(0) { |sum, t| sum + t.amount } %></p>
                    </div>
                    <p class="date-text text-end"><%= l category.created_at.to_date, format: :long %></p>
                </div>
            </div>
        </div>
    <% end %>
</div>
<div class="btn-wrapper d-grid gap-2 d-md-block">
  <button class="btn-main" type="button" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Add Category">
    <%= link_to 'Add Category', new_category_path %>
  </button>
</div>

app/views/categories/most_ancient.html.erb
<div class="nav-card bg-primary">
    <%= render 'devise/shared/nav' %>
    <div class="nav-card-body mx-2">
        <%= link_to 'Oldest', categories_most_ancient_path, class: '' %>
        <%= link_to 'Recent', categories_most_recent_path, class: '' %>
    </div>
</div>
<div class="card">
    <div class="card-body">
    <p>Finances</p>
    </div>
</div>
<div class="row">
    <% @user.most_ancient_categories.each do |category| %>
        <div class="col-md-3">
            <div class="m-3 bg-white category-card">
                <% if category.icon.present? %>
                    <%= image_tag category.icon, class: "catagory-photo" %>
                <% else %>
                    <%= image_tag "category.jpg", class: "catagory-photo" %>
                <% end %>
                <div class="trans-text">
                    <div class="trans-name">
                        <p class=""><%= link_to category.name, category_payments_path(category_id: category.id) %></p>
                        <p class="fw-bold">$<%= Payment.where(category_id: category.id).reduce(0) { |sum, t| sum + t.amount } %></p>
                    </div>
                    <p class="date-text text-end"><%= l category.created_at.to_date, format: :long %></p>
                </div>
            </div>
        </div>
    <% end %>
</div>
<div class="btn-wrapper d-grid gap-2 d-md-block">
  <button class="btn-main" type="button">
    <%= link_to 'Add Category', new_category_path %>
  </button>
</div>

app/views/categories/most_recent.html.erb
<div class="nav-card bg-primary">
    <%= render 'devise/shared/nav' %>
    <div class="nav-card-body mx-2">
        <%= link_to 'Oldest', categories_most_ancient_path, class: '' %>
        <%= link_to 'Recent', categories_most_recent_path, class: '' %>
    </div>
</div>
<div class="card">
    <div class="card-body">
    <p>Finances</p>
    </div>
</div>
<div class="row">
    <% @user.most_recent_categories.each do |category| %>
        <div class="col-md-3">
            <div class="m-3 bg-white category-card">
                <% if category.icon.present? %>
                    <%= image_tag category.icon, class: "catagory-photo" %>
                <% else %>
                    <%= image_tag "category.jpg", class: "catagory-photo" %>
                <% end %>
                    <div class="trans-text">
                        <div class="trans-name">
                            <p class=""><%= link_to category.name, category_payments_path(category_id: category.id) %></p>
                            <p class="fw-bold">$<%= Payment.where(category_id: category.id).reduce(0) { |sum, t| sum + t.amount } %></p>
                        </div>
                        <p class="date-text text-end"><%= l category.created_at.to_date, format: :long %></p>
                    </div>
            </div>
        </div>
    <% end %>
</div>
<div class="btn-wrapper d-grid gap-2 d-md-block">
  <button class="btn-main" type="button">
    <%= link_to 'Add Category', new_category_path %>
  </button>
</div>

app/views/categories/new.html.erb
<%= render 'devise/shared/nav'%>
<div class="card">
    <div class="card-body">
        <%= form_with model: @category, url: categories_path do |f| %>
            <div class="mb-3">
                <%= f.file_field :icon, placeholder: "Add picture", class: "form-control", type:"file", id:"formFile" %>
            </div>
            <%= f.text_field :name, placeholder: "Name", class: "form-control"%>
            <%= f.submit 'Add Category', class: 'btn-form'%>
        <% end %>
    </div>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>